### PR TITLE
First draft End User Documentation for SurveyJS Creator at docs/End-User-Docs.md

### PR DESCRIPTION
**Pull request by dwlazlo**
Hi,
I have been working on some documentation geared toward end-users of SurveyJS. I thought this might complement the video you have already prepared and also provide a location for reference docs.

Please have a look at docs/End-User-Docs.md. I've added a few images and given some written overviews of the toolbox items.

I know I am still missing some of the more detailed information for survey logic, translation and embed.

Of course it's a first draft so any feedback or suggestions welcome.

Best wishes,
David

### CODE REVIEW

**Comment by HenriTroyot** [comment]
Hello Dave,

Thank you for your time and for the contribution proposed.

We have recently put MIT licensing to the survey-creator repository's [docs](https://github.com/surveyjs/survey-creator/tree/master/docs) folder, so the content of this folder is allowed to be filled and modified by enthusiastic persons willing to contribute to our docs.

As for your first draft, I'd like to adjust some moments to a common basis before accepting the PR.

At first, it would be better to use the "SurveyJS" term when referring to our products (instead of "Surveyjs" one).

Then, in your Toolbox section, I think that you mean not a toolbox itself but our adorners feature that allows users to modify survey elements directly in the designer surface. And your [survey_editor_tool_panel.png](https://github.com/surveyjs/survey-creator/blob/0e3fcb88956c07cc3ca329c16aa0892c51deaf17/docs/images/survey_editor_tool_panel.png) image (that now is not linked correctly, due to using hyphen instead of underscore in the link's image name, I think) looks like you do mean adorners.

image

More info about adorners can be found here:
https://surveyjs.io/Documentation/Survey-Creator/?id=#adorners-change-element-properties-on-its-designer-surface

The following our image illustrates this concept:
https://github.com/surveyjs/survey-creator/blob/master/docs/images/builder-adorners.png

One more thing I'd like to admit is that the order of toolbox items in the image is not currently aligned with the order in which these items are listed in the text. Could you bring them in correspondence please?

image


Thank you once again for your work. Waiting for further contributions. :)

Thanks,
Andy

**Comment by dwlazlo** [comment]
Hi Andy, 

First of all thanks for your feedback. It was really helpful.

I think I have addressed all of your points:
1. Surveyjs should be SurveyJS (Sorry for such a simple error)
2. Adorners have now been correctly identified as such
3. The order of toolbox summaries has been brought into line with the toolbox itself.

Hopefully this is enough, but of course let me know if more is needed.

Best wishes,
Dave

**Review by HenriTroyot — CHANGES_REQUESTED** [review]
Dave, thank you for your corrections.

I've made some additional `suggested changes`. You can accept them as is, or discuss them in comments.
They mostly relate to terminology - in particular, I suggest changing 'participant' to 'respondent' and 'tool' to 'survey element'.

Thanks,
Andy

**Comment by dwlazlo** [comment]
Thanks Andy, 

Your suggestions are of course excellent and I have accepted them all.

Let me know if you think anything is missing or requires more work.

Best wishes,
Dave

**Review by HenriTroyot — APPROVED** [review]
Suggested changes are approved. PR to be merged.

**Comment by HenriTroyot** [comment]
A customer contribution to Creator docs aimed at end-users.

**Pull request merged**
