### PR TITLE
Change question names to coincide with the names in demos

### PR DESCRIPTION
**Pull request by RomanTsukanov**

### CODE REVIEW

**Review by andrewtelnov — COMMENTED** [review]
Sorry, I missed this issue. Could we check how these questions are named in competing products?
I am not sure about changing Comment to "Text Area".
"Single Input" -> "Text Entry", we are not only text entry. It is a color and date editor. I would not change it.
Single-choices Matrix and Multiple-choices Matrix, I saw these names in other prouduct(s)
Tag box - no doubt, we should do it.
Boolean - "Yes/No question". I don't know.

We change our examples for a better SEO. I don't like some changes here.

**Comment by ElenaGorbatkova** [comment]
please pause implementation, I have a better idea on how to enhance the toolbox.

ps typeform uses Yes/No for boolean as well:
image

**Comment by ElenaGorbatkova** [comment]
https://docs.google.com/spreadsheets/d/1f5Fh8BoGgRfALkr4-Dr6hA1aHaPVdI-dV-EWhZM7qCw/edit?usp=sharing

**Comment by RomanTsukanov** [comment]
I'm gonna open a fresh one.

**Pull request closed without merging**
