### PR TITLE
V2: Support onDragDropAllow event

### PR DESCRIPTION
**Pull request by dmitrykurmanov**
see https://github.com/surveyjs/survey-creator/issues/2846

didn't create unit test because drag drop emulation doesn't make any sense in unit tests

### CODE REVIEW

**Review by tsv2013 — CHANGES_REQUESTED** [review]
Can we add a unit test here?

**Comment by dmitrykurmanov** [comment]
> didn't create unit test because drag drop emulation doesn't make any sense in unit tests

didn't create unit test because drag drop emulation doesn't make any sense in unit tests

**Comment by tsv2013** [comment]
But we can check event fires and ensure nobody doesn't remove your code:
creator.survey.onDragDropAllow.fire(...)
should toggle creator.onDragDropAllow

as tested @andrewtelnov in this commit https://github.com/surveyjs/survey-creator/commit/990d9656abe36b3c2d46097dcd9043908eeb4e29

**Review by OlgaLarina — APPROVED** [review]

**Review by tsv2013 — APPROVED** [review]

**Comment by tsv2013** [comment]
ok :-) usually we use call count instead of bool to ensure event is not triggered too often

**Pull request merged**
