### PR TITLE
Additional documentation for end-users added to docs/End-User-Guide.md

### PR DESCRIPTION
**Pull request by dwlazlo**
Hi @HenriTroyot , 

I just added some more detailed docs to the end-user guide. It mostly covers conditional logic for the survey elements and a specific use case for logic within a matrix.

Let me know what you think.

Cheers,

Dave

### CODE REVIEW

**Review by HenriTroyot — APPROVED** [review]
Thank you Dave.
We appreciate your help in enhancing SurveyJS Creator documentation. 
Right now I apply your changes and merge your PR.
Later on I'll perform some additional internal actions to make this content available on our website. And maybe I'll add some corrections to the sources if this will be required.

Thanks once again for you contribution,
Andy

**Comment by dwlazlo** [comment]
Thanks Andy, 
Please let me know if you'd like any more input from me going forward with this.
Best wishes,
David

**Comment by HenriTroyot** [comment]
Hello David,

Yes, your input is always welcome and greatly appreciated.
By creating such topics you improve documentation and share information that is useful for many end-users and might be in high demand.

Looking forward to further potential contributions which could be a great help for us. :)

Regards,
Andy

**Comment by dwlazlo** [comment]
Thanks Andy! I hope to help with docs when I can :)

**Pull request merged**
